### ISSUE TITLE
Not able to run with python 3.8

### ISSUE THREAD

**Issue by hkyksk** [philippnormann/nvidia-sniper#117]
Everything seems to work untill you try to run the bot. 

Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.8_3.8.2288.0_x64__qbz5n2kfra8p0\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.8_3.8.2288.0_x64__qbz5n2kfra8p0\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\Hiko\PROJECTS\nvidia-sniper\sniper\__main__.py", line 285, in <module>
    loop.run_until_complete(main())
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.8_3.8.2288.0_x64__qbz5n2kfra8p0\lib\asyncio\base_events.py", line 616, in run_until_complete
    return future.result()
  File "C:\Users\Hiko\PROJECTS\nvidia-sniper\sniper\__main__.py", line 94, in main
    print(const.HEADER)
  File "C:\Users\Hiko\.virtualenvs\nvidia-sniper-hV2eibxb\lib\site-packages\colorama\ansitowin32.py", line 41, in write
    self.__convertor.write(text)
  File "C:\Users\Hiko\.virtualenvs\nvidia-sniper-hV2eibxb\lib\site-packages\colorama\ansitowin32.py", line 162, in write
    self.write_and_convert(text)
  File "C:\Users\Hiko\.virtualenvs\nvidia-sniper-hV2eibxb\lib\site-packages\colorama\ansitowin32.py", line 187, in write_and_convert
    self.write_plain_text(text, cursor, start)
  File "C:\Users\Hiko\.virtualenvs\nvidia-sniper-hV2eibxb\lib\site-packages\colorama\ansitowin32.py", line 195, in write_plain_text
    self.wrapped.write(text[start:end])
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.8_3.8.2288.0_x64__qbz5n2kfra8p0\lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode characters in position 2-5: character maps to <undefined>

**Comment by hkyksk** [comment]
Version 3.8.8

**Comment by hkyksk** [comment]
Seems to work with 3.8.0
