### ISSUE TITLE
Wont launch after install...

### ISSUE THREAD

**Issue by k24voigt** [philippnormann/nvidia-sniper#131]
need some ideas why the bot cant launch everything seems to be installed successfully but give me this after i try to launch

2021-05-05 16:40:53,262 INFO: Launching Firefox using default profile: Profiles/4it0kylj.default-release-1620245470017

**Comment by k24voigt** [comment]
2021-05-05 16:45:38 INFO: Launching Firefox using default profile: Profiles/4it0kylj.default-release-1620245470017
.'(Default)').VersionInfo.ProductVersion was unexpected at this time.
Traceback (most recent call last):
  File "C:\Users\k24\AppData\Local\Programs\Python\Python38\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\k24\AppData\Local\Programs\Python\Python38\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\k24\Documents\nvidia-sniper\sniper\__main__.py", line 285, in <module>
    loop.run_until_complete(main())
  File "C:\Users\k24\AppData\Local\Programs\Python\Python38\lib\asyncio\base_events.py", line 616, in run_until_complete
    return future.result()
  File "C:\Users\k24\Documents\nvidia-sniper\sniper\__main__.py", line 99, in main
    driver = webdriver.create()
  File "C:\Users\k24\Documents\nvidia-sniper\sniper\webdriver.py", line 55, in create
    firefox_profile=profile, executable_path=GeckoDriverManager().install())
  File "C:\Users\k24\.virtualenvs\nvidia-sniper-4lKBC0c6\lib\site-packages\webdriver_manager\firefox.py", line 22, in __init__
    self.driver = GeckoDriver(version=version,
  File "C:\Users\k24\.virtualenvs\nvidia-sniper-4lKBC0c6\lib\site-packages\webdriver_manager\driver.py", line 83, in __init__
    self.browser_version = firefox_version()
  File "C:\Users\k24\.virtualenvs\nvidia-sniper-4lKBC0c6\lib\site-packages\webdriver_manager\utils.py", line 164, in firefox_version
    raise ValueError(f'Could not get version for Firefox with this command: {cmd}')
ValueError: Could not get version for Firefox with this command: (Get-Item (Get-ItemProperty 'HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\App Paths\firefox.exe').'(Default)').VersionInfo.ProductVersion

**Comment by alexanderjacuna** [comment]
The last line looks to be a command that can be run in Windows PowerShell. I am getting the same error and can run the command just fine.

ValueError: Could not get version for Firefox with this command: (Get-Item (Get-ItemProperty 'HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\App Paths\firefox.exe').'(Default)').VersionInfo.ProductVersion


PS C:\Users\Alexander> (Get-Item (Get-ItemProperty 'HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\App Paths\firefox.exe').'(Default)').VersionInfo.ProductVersion
88.0.1

**Comment by Dommm56** [comment]
Same error here:
, line 164, in firefox_version
    raise ValueError(f'Could not get version for Firefox with this command: {cmd}')
ValueError: Could not get version for Firefox with this command: (Get-Item (Get-ItemProperty 'HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\App Paths\firefox.exe').'(Default)').VersionInfo.ProductVersion

Some kind of version error? som1 got a fix?

**Comment by BBBBBbruce** [comment]
getting same error both in cmd and powershell.
