### ISSUE TITLE
Runtime error after 1 hour

### ISSUE THREAD

**Issue by SlideeScherz** [philippnormann/nvidia-sniper#144]
After about 1 hour every time I execute I receive; **RuntimeError: Event loop is closed**

Here is the full log of my terminal 

[Sniper Error.txt](https://github.com/philippnormann/nvidia-sniper/files/6689850/Sniper.Error.txt)

**Comment by digital-dev** [comment]
Can confirm, I get the same error after around an hour. This happens consistently.

Running Windows 10 20H2 Fully updated, Vmware running only the required applications.

```
Traceback (most recent call last):
  File "C:\Python38\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Python38\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "c:\Users\username\Documents\nvidia-sniper\sniper\__main__.py", line 285, in <module>
    loop.run_until_complete(main())
  File "C:\Python38\lib\asyncio\base_events.py", line 616, in run_until_complete
    return future.result()
  File "c:\Users\username\Documents\nvidia-sniper\sniper\__main__.py", line 163, in main
    status = await api_client.check_availability(target_id)
  File "c:\Users\username\Documents\nvidia-sniper\sniper\api.py", line 28, in check_availability
    async with self.session.get(f'{const.INVENTORY_URL}/{self.dr_locale}/{self.api_currency}/{dr_id}') as response:
  File "C:\Users\username\Documents\nvidia-sniper\.venv\lib\site-packages\aiohttp\client.py", line 1117, in __aenter__
    self._resp = await self._coro
  File "C:\Users\username\Documents\nvidia-sniper\.venv\lib\site-packages\aiohttp\client.py", line 544, in _request
    await resp.start(conn)
  File "C:\Users\username\Documents\nvidia-sniper\.venv\lib\site-packages\aiohttp\client_reqrep.py", line 905, in start
    self._continue = None
  File "C:\Users\username\Documents\nvidia-sniper\.venv\lib\site-packages\aiohttp\helpers.py", line 656, in __exit__
    raise asyncio.TimeoutError from None
asyncio.exceptions.TimeoutError
Exception ignored in: <function _ProactorBasePipeTransport.__del__ at 0x00000235A9449DC0>
Traceback (most recent call last):
  File "C:\Python38\lib\asyncio\proactor_events.py", line 116, in __del__
  File "C:\Python38\lib\asyncio\proactor_events.py", line 108, in close
  File "C:\Python38\lib\asyncio\base_events.py", line 719, in call_soon
  File "C:\Python38\lib\asyncio\base_events.py", line 508, in _check_closed
RuntimeError: Event loop is closed
```

**Comment by JoshuaMunoz** [comment]
Same! I have to keep restarting the bot once it stops itself.
