### ISSUE TITLE
Failed to Get inventory Status using API

### ISSUE THREAD

**Issue by Nostragamus** [philippnormann/nvidia-sniper#19]
Running on windows, getting this error when checking for inventory with API

2020-09-25 17:22:34,820 nvidia-sniper: Checking en-us availability for GeForce RTX 3080 using selenium...
2020-09-25 17:22:53,622 nvidia-sniper: GPU currently not available
2020-09-25 17:22:53,622 nvidia-sniper: Checking en-us availability for GeForce RTX 3080 using API...
2020-09-25 17:23:12,158 nvidia-sniper: Failed to get inventory status for 5438481700
Traceback (most recent call last):
  File "C:\nvidia-sniper\sniper\__main__.py", line 47, in checkout_api
    inventory = await api.get_inventory_status(session, dr_locale, api_currency, dr_id)
  File "C:\nvidia-sniper\sniper\api.py", line 22, in get_inventory_status
    json_resp = await response.json()
  File "C:\Users\usr\.virtualenvs\nvidia-sniper-Fu40Ck5x\lib\site-packages\aiohttp\client_reqrep.py", line 1026, in json
    raise ContentTypeError(
aiohttp.client_exceptions.ContentTypeError: 0, message='Attempt to decode JSON with unexpected mimetype: text/html', url=URL('https://api-prod.nvidia.com/direct-sales-shop/DR/products//en_us/USD/5438481700')

**Comment by drx19** [comment]
I get that error too.

**Comment by LonleyViper** [comment]
using mac, having the same issue. I suspect its that they changed up their API. 

`2020-09-26 14:37:37,832 nvidia-sniper: Failed to get inventory status for 5438792700
Traceback (most recent call last):
  File "/Users/adamchanning/Documents/nvidia-sniper/sniper/__main__.py", line 47, in checkout_api
    inventory = await api.get_inventory_status(session, dr_locale, api_currency, dr_id)
  File "/Users/adamchanning/Documents/nvidia-sniper/sniper/api.py", line 22, in get_inventory_status
    json_resp = await response.json()
  File "/Users/adamchanning/.local/share/virtualenvs/nvidia-sniper-V5mCHnvd/lib/python3.8/site-packages/aiohttp/client_reqrep.py", line 1026, in json
    raise ContentTypeError(
aiohttp.client_exceptions.ContentTypeError: 0, message='Attempt to decode JSON with unexpected mimetype: text/html', url=URL('https://api-prod.nvidia.com/direct-sales-shop/DR/products/en_gb/GBP/5438792700')
`

**Comment by philippnormann** [comment]
The API and online store are both down for maintenance at the moment, so these errors are expected. I agree, that the error messages could be improved though :+1: Throwing stack traces at users is probably not such a good idea :sweat_smile:
