### ISSUE TITLE
bug: Selenium error when running on Arch or Gentoo flavor of linux

### ISSUE THREAD

**Issue by Agentscreech** [philippnormann/nvidia-sniper#50]
There is a bug in geckodriver where any system that replaces /usr/bin/firefox with a script that executes the real binary will fail

Failure will present like this
```
[WDM] - Driver [/home/<USER>/.wdm/drivers/geckodriver/linux64/v0.27.0/geckodriver] found in cache
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/<USER>/projects/nvidia-sniper/sniper/__main__.py", line 46, in <module>
    driver = webdriver.create()
  File "/home/<USER>/projects/nvidia-sniper/sniper/webdriver.py", line 38, in create
    return webdriver.Firefox(firefox_profile=profile, executable_path=GeckoDriverManager().install())
  File "/home/<USER>/.local/share/virtualenvs/nvidia-sniper-g1iyIxjU/lib/python3.8/site-packages/selenium/webdriver/firefox/webdriver.py", line 170, in __init__
    RemoteWebDriver.__init__(
  File "/home/<USER>/.local/share/virtualenvs/nvidia-sniper-g1iyIxjU/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 157, in __init__
    self.start_session(capabilities, browser_profile)
  File "/home/<USER>/.local/share/virtualenvs/nvidia-sniper-g1iyIxjU/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 252, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "/home/<USER>/.local/share/virtualenvs/nvidia-sniper-g1iyIxjU/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/<USER>/.local/share/virtualenvs/nvidia-sniper-g1iyIxjU/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.SessionNotCreatedException: Message: Unable to find a matching set of capabilities
```

It is mentioned here:
https://github.com/SeleniumHQ/selenium/issues/8604
Despite the last comment there, upstream doesn't seem to be tracking it at geckodriver. Adding the path to the actual firefox binary into $PATH works around the issue on Gentoo Linux. In specific, I can launch nvidia sniper using `PATH="/usr/lib64/firefox:$PATH" pipenv run python -m sniper`.

**Comment by philippnormann** [comment]
Hey @Agentscreech, thanks for the heads up! Do you have any idea how we can fix or work around this issue? :thinking:

**Comment by philippnormann** [comment]
I’m closing this issue for now because of inactivity...
