### ISSUE TITLE
Bug: WebDriverException: Failed to decode response from marionette

### ISSUE THREAD

**Issue by LonleyViper** [philippnormann/nvidia-sniper#60]
Got this exception after 12ish hours of running. No obvious cause apart from Firefox appearing to be closed when I returned.

```2020-10-06 06:40:26,869 nvidia-sniper: Checking en-gb availability for GeForce RTX 3090 using selenium...
Traceback (most recent call last):

  File "c:\users\<username>\appdata\local\programs\python\python38-32\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,

  File "c:\users\<username>\appdata\local\programs\python\python38-32\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)

  File "C:\Users\<username>\Desktop\nvidia-sniper\sniper\__main__.py", line 269, in <module>
    loop.run_until_complete(main())

  File "c:\users\<username>\appdata\local\programs\python\python38-32\lib\asyncio\base_events.py", line 616, in run_until_complete

    return future.result()

  File "C:\Users\<username>\Desktop\nvidia-sniper\sniper\__main__.py", line 230, in main
    checkout_reached = checkout_selenium(

  File "C:\Users\<username>\Desktop\nvidia-sniper\sniper\__main__.py", line 102, in checkout_selenium
    gpu_available = nvidia.check_availability(driver, timeout)

  File "C:\Users\<username>\Desktop\nvidia-sniper\sniper\nvidia.py", line 40, in check_availability
    WebDriverWait(driver, timeout).until(add_to_basket_clickable)

  File "C:\Users\<username>\.virtualenvs\nvidia-sniper-e_ejhjj8\lib\site-packages\selenium\webdriver\support\wait.py", line 71, in until
    value = method(self._driver)

  File "C:\Users\<username>\.virtualenvs\nvidia-sniper-e_ejhjj8\lib\site-packages\selenium\webdriver\support\expected_conditions.py", line 297, in __call__
    element = visibility_of_element_located(self.locator)(driver)

  File "C:\Users\<username>\.virtualenvs\nvidia-sniper-e_ejhjj8\lib\site-packages\selenium\webdriver\support\expected_conditions.py", line 128, in __call__
    return _element_if_visible(_find_element(driver, self.locator))

  File "C:\Users\<username>\.virtualenvs\nvidia-sniper-e_ejhjj8\lib\site-packages\selenium\webdriver\support\expected_conditions.py", line 415, in _find_element
    raise e

  File "C:\Users\<username>\.virtualenvs\nvidia-sniper-e_ejhjj8\lib\site-packages\selenium\webdriver\support\expected_conditions.py", line 411, in _find_element
    return driver.find_element(*by)

  File "C:\Users\<username>\.virtualenvs\nvidia-sniper-e_ejhjj8\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 976, in find_element
    return self.execute(Command.FIND_ELEMENT, {

  File "C:\Users\<username>\.virtualenvs\nvidia-sniper-e_ejhjj8\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)

  File "C:\Users\<username>\.virtualenvs\nvidia-sniper-e_ejhjj8\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: Failed to decode response from marionette```

**Comment by philippnormann** [comment]
Seems like Firefox crashed or was closed due to some other reason :thinking:

**Comment by philippnormann** [comment]
I’m closing this issue for now because of inactivity...
