### ISSUE TITLE
SyntaxError: invalid syntax

### ISSUE THREAD

**Issue by 21796114** [philippnormann/nvidia-sniper#84]
Hello there . Me again. I uploaded the _main_.py file you updated 1 hour ago. I am getting the following error:

Traceback (most recent call last):
   File "c: \ users \ pc \ appdata \ local \ programs \ python \ python38 \ lib \ runpy.py", line 185, in _run_module_as_main
     mod_name, mod_spec, code = _get_module_details (mod_name, _Error)
   File "c: \ users \ pc \ appdata \ local \ programs \ python \ python38 \ lib \ runpy.py", line 144, in _get_module_details
     return _get_module_details (pkg_main_name, error)
   File "c: \ users \ pc \ appdata \ local \ programs \ python \ python38 \ lib \ runpy.py", line 155, in _get_module_details
     code = loader.get_code (mod_name)
   File "<frozen importlib._bootstrap_external>", line 916, in get_code
   File "<frozen importlib._bootstrap_external>", line 846, in source_to_code
   File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
   File "C: \ nvidia-sniper \ sniper \ __ main__.py", line 6
     <! DOCTYPE html>
     ^
SyntaxError: invalid syntax

What should I do ?

**Comment by philippnormann** [comment]
It seems like you modified the code in `sniper/__ main__.py`. You can reset local changes using `git stash` and try again.

**Comment by 21796114** [comment]
Fixed. Thanks.
